import {aimToScreen} from './aimEngine.js';
export class AimRenderer{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.dpr=Math.min(devicePixelRatio||1,2);this.resize();window.addEventListener('resize',()=>this.resize())}
 resize(){const r=this.canvas.getBoundingClientRect();this.canvas.width=Math.max(1,Math.floor(r.width*this.dpr));this.canvas.height=Math.max(1,Math.floor(r.height*this.dpr));this.ctx.setTransform(this.dpr,0,0,this.dpr,0,0);this.width=r.width;this.height=r.height}
 clear(){this.ctx.fillStyle='#0a1018';this.ctx.fillRect(0,0,this.width,this.height)}
 drawGrid(){const c=this.ctx;c.save();c.globalAlpha=.1;c.strokeStyle='#9eabc0';for(let x=0;x<this.width;x+=60){c.beginPath();c.moveTo(x,0);c.lineTo(x,this.height);c.stroke()}for(let y=0;y<this.height;y+=60){c.beginPath();c.moveTo(0,y);c.lineTo(this.width,y);c.stroke()}c.restore()}
 drawTarget(target,yawOffset=0,pitchOffset=0,fov=90,active=true){const p=aimToScreen(target.worldYaw-yawOffset,target.worldPitch-pitchOffset,this.width,this.height,fov);const c=this.ctx;c.beginPath();c.arc(p.x,p.y,target.radius,0,Math.PI*2);c.fillStyle=active?'#dce9ff':'#50617c';c.fill();c.lineWidth=2;c.strokeStyle='#77a7ff';c.stroke();c.beginPath();c.arc(p.x,p.y,3,0,Math.PI*2);c.fillStyle='#101825';c.fill()}
}
export function drawLineChart(canvas,series,labels){const ctx=canvas.getContext('2d'),w=canvas.clientWidth,h=canvas.clientHeight||290,dpr=devicePixelRatio||1;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#283449';ctx.lineWidth=1;for(let i=0;i<5;i++){const y=24+i*(h-50)/4;ctx.beginPath();ctx.moveTo(38,y);ctx.lineTo(w-15,y);ctx.stroke()}series.forEach((s,si)=>{ctx.beginPath();s.values.forEach((v,i)=>{const x=42+i*(w-65)/Math.max(1,s.values.length-1),y=h-28-(v/100)*(h-56);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=si===0?'#77a7ff':'#9a7cff';ctx.lineWidth=2;ctx.stroke()});ctx.fillStyle='#8391a8';ctx.font='10px Inter';[0,25,50,75,100].forEach((v,i)=>ctx.fillText(String(v),8,h-27-i*(h-56)/4));if(labels?.length)ctx.fillText(labels[0],42,h-8)}
